# Generated by Django 6.0.1 on 2026-08-26 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileManagement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=200, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True)),
                ('code_file', models.FileField(blank=True, null=True, upload_to='file/code')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='file/documents/')),
                ('arsip_file', models.FileField(blank=True, null=True, upload_to='file/arsip')),
                ('executable_file', models.FileField(blank=True, null=True, upload_to='file/executable')),
                ('image_file', models.FileField(blank=True, null=True, upload_to='file/image')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fileManagement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
