# Generated by Django 5.2.5 on 2025-09-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fileManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True)),
                ('fileName', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=200, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True)),
                ('code_file', models.FileField(blank=True, null=True, upload_to='media/file/code')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='media/file/documents/')),
                ('arsip_file', models.FileField(blank=True, null=True, upload_to='media/file/arsip')),
                ('executable_file', models.FileField(blank=True, null=True, upload_to='media/file/executable')),
                ('image_file', models.FileField(blank=True, null=True, upload_to='media/file/image')),
            ],
        ),
    ]
