# Generated by Django 6.0.1 on 2026-01-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filemanagement",
            name="arsip_file",
            field=models.FileField(blank=True, null=True, upload_to="file/arsip"),
        ),
        migrations.AlterField(
            model_name="filemanagement",
            name="code_file",
            field=models.FileField(blank=True, null=True, upload_to="file/code"),
        ),
        migrations.AlterField(
            model_name="filemanagement",
            name="create_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="filemanagement",
            name="document_file",
            field=models.FileField(blank=True, null=True, upload_to="file/documents/"),
        ),
        migrations.AlterField(
            model_name="filemanagement",
            name="executable_file",
            field=models.FileField(blank=True, null=True, upload_to="file/executable"),
        ),
        migrations.AlterField(
            model_name="filemanagement",
            name="image_file",
            field=models.FileField(blank=True, null=True, upload_to="file/image"),
        ),
    ]
