# Generated by Django 6.0.1 on 2026-01-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_filemanagement_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="filemanagement",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="filemanagement",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
